name: ticket
on:
  schedule:
    - cron: '*/1 * * * *' # Every 1 minutes
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 210972
          schedule-id: 100001
          seat-id: 1_0
          slack-incoming-webhook-url: 'https://hooks.slack.com/services/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'
          message: 'hello'
