name: ticket
on:
  schedule:
    - cron: '*/4 * * * *' # Every 1 minutes
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: '211992'
          schedule-id: '100001'
          seat-id: 'A,B,C,D,E,F,I,J,K,L,M,N,F1,F2'
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: '!!!!!'
